Repository CodeVault-CV/Server, pull requests merged in 2022-03, with the labels that each got.

#14 #13 feat: Setting Spring Security and make custom JWT Filter
  build.gradle
  src/main/java/com/example/algoproject/security/CustomUserDetailsService.java
  src/main/java/com/example/algoproject/security/JWTAuthenticationFilter.java
  src/main/java/com/example/algoproject/security/JWTUtil.java
  src/main/java/com/example/algoproject/security/SecurityConfig.java
  src/main/java/com/example/algoproject/user/controller/UserController.java
  src/main/java/com/example/algoproject/user/dto/CustomUserDetailsVO.java
  src/main/java/com/example/algoproject/user/service/UserService.java
  src/main/java/com/example/algoproject/util/JWTUtil.java
Labels: enhancement

#16 Feat/15
  build.gradle
  src/main/java/com/example/algoproject/config/SwaggerConfig.java
  src/main/java/com/example/algoproject/errors/ErrorResponse.java
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/SuccessResponse.java
  src/main/java/com/example/algoproject/errors/exception/NotExistStudyException.java
  src/main/java/com/example/algoproject/errors/exception/NotExistUserException.java
  src/main/java/com/example/algoproject/security/SecurityConfig.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/domain/BelongsTo.java
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/dto/AddContributorRequest.java
  src/main/java/com/example/algoproject/study/dto/AddMemberRequest.java
  src/main/java/com/example/algoproject/study/dto/CreateRepositoryRequest.java
  src/main/java/com/example/algoproject/study/dto/MemberInfoResponse.java
  src/main/java/com/example/algoproject/study/dto/MemberListRequest.java
  src/main/java/com/example/algoproject/study/repository/BelongsToRepository.java
  src/main/java/com/example/algoproject/study/repository/StudyRepository.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/controller/UserController.java
  src/main/java/com/example/algoproject/user/domain/User.java
  src/main/java/com/example/algoproject/user/repository/UserRepository.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: enhancement, refactoring

#21 #20 refactoring: refactoring login response
  src/main/java/com/example/algoproject/user/controller/UserController.java
  src/main/java/com/example/algoproject/user/dto/LoginResponse.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: refactoring

#23 #22 feat: add cors to SecurityConfig
  src/main/java/com/example/algoproject/security/SecurityConfig.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: enhancement

#27 #24 refactoring: refactoring user profile
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/domain/User.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: refactoring

#33 #31 feat: add transactional annotation to studyservice
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: enhancement

#35 #34 refactoring: refactoring public to private
  src/main/java/com/example/algoproject/study/domain/BelongsTo.java
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/dto/AddContributorRequest.java
  src/main/java/com/example/algoproject/study/dto/AddMemberRequest.java
  src/main/java/com/example/algoproject/study/dto/CreateRepositoryRequest.java
  src/main/java/com/example/algoproject/study/dto/MemberInfoResponse.java
  src/main/java/com/example/algoproject/study/dto/MemberListRequest.java
  src/main/java/com/example/algoproject/study/dto/StudyInfoResponse.java
  src/main/java/com/example/algoproject/user/dto/LoginResponse.java
  src/main/java/com/example/algoproject/user/dto/TokenResponse.java
  src/main/java/com/example/algoproject/user/dto/UserProfileResponse.java
Labels: refactoring

#37 #36 feat: add get study list
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/repository/BelongsToRepository.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: enhancement

#39 #38 refactoring: refactoring study field
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/dto/request/AddContributorRequest.java
  src/main/java/com/example/algoproject/study/dto/request/AddMemberRequest.java
  src/main/java/com/example/algoproject/study/dto/request/CreateRepositoryRequest.java
  src/main/java/com/example/algoproject/study/dto/request/CreateStudyRequest.java
  src/main/java/com/example/algoproject/study/dto/request/MemberListRequest.java
  src/main/java/com/example/algoproject/study/dto/response/MemberInfoResponse.java
  src/main/java/com/example/algoproject/study/dto/response/StudyInfoResponse.java
  src/main/java/com/example/algoproject/study/repository/StudyRepository.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: refactoring
