Repository CodeVault-CV/Server, pull requests merged in 2022-08, with the labels that each got.

#94 #93 refactoring: refactoring access rights
  src/main/java/com/example/algoproject/errors/exception/badrequest/NotMySolutionException.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#96 #95 refactoring: refactoring problem enum
  src/main/java/com/example/algoproject/problem/domain/Platform.java
  src/main/java/com/example/algoproject/problem/domain/Problem.java
Labels: refactoring

#102 #97 refactoring: update transactional
  src/main/java/com/example/algoproject/belongsto/service/BelongsToService.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: refactoring

#103 #100 feat: create github service
  src/main/java/com/example/algoproject/github/dto/request/CreateWebhook.java
  src/main/java/com/example/algoproject/github/dto/request/TokenDto.java
  src/main/java/com/example/algoproject/github/dto/request/WebhookConfig.java
  src/main/java/com/example/algoproject/github/service/GithubService.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: enhancement, refactoring

#104 #100 feat: update url at security config
  src/main/java/com/example/algoproject/security/SecurityConfig.java
Labels: bug

#106 #105 bug: remove content type in solution
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
Labels: bug

#108 #107 bug: add large object annotation
  src/main/java/com/example/algoproject/solution/domain/Solution.java
Labels: bug

#110 #109 refactoring: refactoring solutiuon
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/domain/Solution.java
Labels: refactoring

#112 #109 refactoring: add custom exception
  src/main/java/com/example/algoproject/security/CustomUserDetailsService.java
Labels: refactoring

#114 #113 refactoring: create inheritance in custom exception
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyDeleteSolutionException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyExistMemberException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyExistRepositoryNameException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyExistSolutionException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/BadRequestException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/NotMatchProblemAndSolutionException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/NotMySolutionException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/NotWriterUserException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/SameNameException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/SameUserException.java
  src/main/java/com/example/algoproject/errors/exception/forbidden/ForbiddenException.java
  src/main/java/com/example/algoproject/errors/exception/forbidden/NotLeaderUserException.java
  src/main/java/com/example/algoproject/errors/exception/forbidden/StudyAuthException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistCommentException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistMemberException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistProblemException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistRepositoryException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistSessionException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistSolutionException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistStudyException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotExistUserException.java
  src/main/java/com/example/algoproject/errors/exception/notfound/NotFoundException.java
  src/main/java/com/example/algoproject/errors/exception/unauthorized/FailedResponseException.java
  src/main/java/com/example/algoproject/errors/exception/unauthorized/UnauthorizedException.java
  src/main/java/com/example/algoproject/security/JWTUtil.java
Labels: refactoring

#117 #116 refactoring: change user name to user id
  src/main/java/com/example/algoproject/user/controller/UserController.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: refactoring

#118 #115 refactoring: change solution response
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#120 #115 refactoring: change solution response
  src/main/java/com/example/algoproject/solution/dto/response/SolutionDTO.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#121 #115 refactoring: change solution response
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionListInfo.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#122 #99 refactoring: refactoring Platform url
  src/main/java/com/example/algoproject/problem/domain/Platform.java
  src/main/java/com/example/algoproject/problem/domain/Problem.java
  src/main/java/com/example/algoproject/user/dto/LoginDto.java
Labels: refactoring

#123 #119 feat: add review list api
  src/main/java/com/example/algoproject/review/controller/ReviewController.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionDTO.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: enhancement

#124 #113 refactoring: remove unnecessary method
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
Labels: refactoring

#126 #125 feat: add leader auth api
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: enhancement

#128 #127 refactoring: add language in solution detail response
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#130 #129 refactoring: change requestbody to requestparam
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/dto/request/SearchUser.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: refactoring

#132 #131 refactoring: move github method to GithubService
  src/main/java/com/example/algoproject/github/service/GithubService.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#134 #133 refactoring: remove unnecessary session save
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
Labels: refactoring

#136 Feat/98
  src/main/java/com/example/algoproject/problem/controller/ProblemController.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/review/controller/ReviewController.java
  src/main/java/com/example/algoproject/review/domain/Review.java
  src/main/java/com/example/algoproject/review/dto/request/AddReview.java
  src/main/java/com/example/algoproject/review/dto/request/DeleteReview.java
  src/main/java/com/example/algoproject/review/dto/request/UpdateReview.java
  src/main/java/com/example/algoproject/review/dto/response/ReviewInfo.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
  src/main/java/com/example/algoproject/session/controller/SessionController.java
  src/main/java/com/example/algoproject/session/dto/request/UpdateSession.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/domain/Solution.java
  src/main/java/com/example/algoproject/solution/dto/request/DeleteSolution.java
  src/main/java/com/example/algoproject/solution/dto/request/UpdateSolution.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionListInfo.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/dto/request/UpdateStudy.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/service/UserService.java
  src/main/java/com/example/algoproject/util/Auth.java
  src/main/java/com/example/algoproject/util/Interceptor.java
Labels: enhancement, refactoring

#138 #137: update api operation
  src/main/java/com/example/algoproject/review/controller/ReviewController.java
  src/main/java/com/example/algoproject/review/dto/request/DeleteReview.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionDTO.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: refactoring

#141 #135 refactoring: Delete Solutions Related Session And Problem
  src/main/java/com/example/algoproject/github/service/GithubService.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/util/PathUtil.java
Labels: refactoring

#143 #142 fix: fix conflicts
  src/main/java/com/example/algoproject/problem/controller/ProblemController.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/session/controller/SessionController.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: bug

#145 #144 feat: add gradle-wrapper.jar
  .gitignore
Labels: enhancement

#146 #144 feat: add gradle-wrapper.jar
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: enhancement

#148 #147 bug : Fix Review Time
  src/main/java/com/example/algoproject/review/domain/Review.java
  src/main/java/com/example/algoproject/review/dto/response/ReviewInfo.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
Labels: bug

#150 #149 refactoring: change commit maessage
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/util/PathUtil.java
Labels: refactoring

#152 #151 bug: fix create study bug
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: bug
