Repository CodeVault-CV/Server, pull requests merged in 2022-07, with the labels that each got.

#64 #58 feat: add session & update problem
  src/main/java/com/example/algoproject/belongsto/domain/BelongsTo.java
  src/main/java/com/example/algoproject/comment/controller/CommentController.java
  src/main/java/com/example/algoproject/comment/repository/CommentRepository.java
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/NotExistSessionException.java
  src/main/java/com/example/algoproject/errors/exception/NotExistSolutionException.java
  src/main/java/com/example/algoproject/problem/controller/ProblemController.java
  src/main/java/com/example/algoproject/problem/domain/Platform.java
  src/main/java/com/example/algoproject/problem/domain/Problem.java
  src/main/java/com/example/algoproject/problem/dto/request/AddProblem.java
  src/main/java/com/example/algoproject/problem/dto/response/ProblemInfo.java
  src/main/java/com/example/algoproject/problem/repository/ProblemRepository.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/review/controller/ReviewController.java
  src/main/java/com/example/algoproject/review/domain/Review.java
  src/main/java/com/example/algoproject/review/dto/AddReview.java
  src/main/java/com/example/algoproject/review/dto/UpdateReview.java
  src/main/java/com/example/algoproject/review/repository/ReviewRepository.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
  src/main/java/com/example/algoproject/session/controller/SessionController.java
  src/main/java/com/example/algoproject/session/domain/Session.java
  src/main/java/com/example/algoproject/session/dto/request/CreateSession.java
  src/main/java/com/example/algoproject/session/dto/request/UpdateSession.java
  src/main/java/com/example/algoproject/session/dto/response/SessionInfo.java
  src/main/java/com/example/algoproject/session/repository/SessionRepository.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/solution/domain/Solution.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/repository/SolutionRepository.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/domain/Study.java
  src/main/java/com/example/algoproject/study/dto/response/StudyInfo.java
  src/main/java/com/example/algoproject/user/domain/User.java
Labels: enhancement

#67 #59 feat: update spring & swagger version
  build.gradle
  src/main/java/com/example/algoproject/config/SwaggerConfig.java
  src/main/java/com/example/algoproject/problem/controller/ProblemController.java
  src/main/java/com/example/algoproject/review/controller/ReviewController.java
  src/main/java/com/example/algoproject/security/SecurityConfig.java
  src/main/java/com/example/algoproject/session/controller/SessionController.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/user/controller/UserController.java
Labels: enhancement, refactoring

#68 #59 refactoring: security config refactoring
  src/main/java/com/example/algoproject/security/SecurityConfig.java
Labels: refactoring

#71 #70 refactoring: refactoring user
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/review/service/ReviewService.java
  src/main/java/com/example/algoproject/security/CustomUserDetailsService.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
  src/main/java/com/example/algoproject/user/controller/UserController.java
  src/main/java/com/example/algoproject/user/domain/User.java
  src/main/java/com/example/algoproject/user/dto/CustomUserDetailsVO.java
  src/main/java/com/example/algoproject/user/repository/UserRepository.java
  src/main/java/com/example/algoproject/user/service/UserService.java
Labels: refactoring

#73 #72 feat: add interceptor
  src/main/java/com/example/algoproject/config/WebConfig.java
  src/main/java/com/example/algoproject/util/Interceptor.java
Labels: enhancement

#74 #69 feat: add solution list & delete api
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/NotMySolutionException.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/domain/Language.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionListInfo.java
  src/main/java/com/example/algoproject/solution/repository/SolutionRepository.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: enhancement

#77 #refactoring: refactoring solution
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/AlreadyExistSolutionException.java
  src/main/java/com/example/algoproject/s3/S3Uploader.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/domain/Solution.java
  src/main/java/com/example/algoproject/solution/dto/request/AddSolution.java
  src/main/java/com/example/algoproject/solution/dto/request/UpdateSolution.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionInfo.java
  src/main/java/com/example/algoproject/solution/dto/response/SolutionListInfo.java
  src/main/java/com/example/algoproject/solution/repository/SolutionRepository.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/util/PathUtil.java
  src/main/java/com/example/algoproject/util/ReadMeUtil.java
Labels: refactoring

#79 #75 refactoring: fix conflict
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyExistSolutionException.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: bug

#82 #81 refactoring: refactoring session
  src/main/java/com/example/algoproject/session/controller/SessionController.java
  src/main/java/com/example/algoproject/session/domain/Session.java
  src/main/java/com/example/algoproject/session/dto/request/CreateSession.java
  src/main/java/com/example/algoproject/session/dto/request/UpdateSession.java
  src/main/java/com/example/algoproject/session/service/SessionService.java
  src/main/java/com/example/algoproject/study/controller/StudyController.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: enhancement, refactoring

#84 #83 bug: fix session & study
  src/main/java/com/example/algoproject/session/domain/Session.java
  src/main/java/com/example/algoproject/study/dto/request/CreateStudy.java
Labels: bug

#86 #85 refactoring: refactoring problem
  src/main/java/com/example/algoproject/problem/controller/ProblemController.java
  src/main/java/com/example/algoproject/problem/domain/Problem.java
  src/main/java/com/example/algoproject/problem/dto/request/ProblemWeekList.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
  src/main/java/com/example/algoproject/security/SecurityConfig.java
Labels: refactoring

#87 #85 refactoring: remove solution list at problem info
  src/main/java/com/example/algoproject/problem/dto/response/ProblemInfo.java
Labels: refactoring

#80 #76 refactoring: refactoring solution
  src/main/java/com/example/algoproject/errors/GlobalExceptionHandler.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/AlreadyDeleteSolutionException.java
  src/main/java/com/example/algoproject/errors/exception/badrequest/NotMatchProblemAndSolutionException.java
  src/main/java/com/example/algoproject/solution/controller/SolutionController.java
  src/main/java/com/example/algoproject/solution/domain/Language.java
  src/main/java/com/example/algoproject/solution/domain/Solution.java
  src/main/java/com/example/algoproject/solution/dto/request/DeleteSolution.java
  src/main/java/com/example/algoproject/solution/repository/SolutionRepository.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
  src/main/java/com/example/algoproject/study/dto/request/CreateWebhook.java
  src/main/java/com/example/algoproject/study/service/StudyService.java
Labels: refactoring

#88 #85 refactoring: update problem list api
  src/main/java/com/example/algoproject/problem/repository/ProblemRepository.java
  src/main/java/com/example/algoproject/problem/service/ProblemService.java
Labels: refactoring

#89 #76 refactoring: refactoring solution webhook
  src/main/java/com/example/algoproject/solution/repository/SolutionRepository.java
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#91 #76 refactoring: refactoring solution delete webhook
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring

#92 #76 fix: fix solution delete webhook
  src/main/java/com/example/algoproject/solution/service/SolutionService.java
Labels: refactoring
